import React from 'react';
import { GameType } from '../../../../shared/types';
import {
  Crown,
  Anchor,
  Grid,
  Disc,
  ShieldAlert,
  Columns,
  Boxes,
  Hexagon,
  Gamepad2,
  CircleDot,
  RefreshCw,
  Type,
  TrendingUp,
  Calculator,
  Hash,
  Sparkles,
  Dices,
} from 'lucide-react';

export interface GameDefinition {
  id: GameType;
  name: string;
  description: string;
  icon: React.ComponentType<{ className?: string }>;
  category?: 'Classic' | 'Strategy' | 'Cards' | 'Board' | 'Arcade';
  themeColor: 'blue' | 'purple' | 'emerald' | 'amber' | 'rose' | 'indigo' | 'cyan' | 'fuchsia' | 'teal';
  bgGradient: string;
  borderColor: string;
  activeBorder: string;
  ringColor: string;
  iconBg: string;
  iconColor: string;
  badgeVariant: 'blue' | 'purple' | 'emerald' | 'amber' | 'rose';
  isImplemented?: boolean;
}

export const AVAILABLE_GAMES: GameDefinition[] = [
  {
    id: 'backgammon',
    name: 'BACKGAMMON',
    description: 'Ancient strategy race game',
    icon: Dices,
    category: 'Board',
    themeColor: 'amber',
    bgGradient: 'from-amber-950/60 via-slate-900 to-slate-950',
    borderColor: 'border-amber-500/30',
    activeBorder: 'border-amber-500',
    ringColor: 'ring-amber-500/50 shadow-amber-500/20',
    iconBg: 'bg-amber-500/20 border-amber-500/40',
    iconColor: 'text-amber-400',
    badgeVariant: 'amber',
    isImplemented: false,
  },
  {
    id: 'battleship',
    name: 'BATTLESHIP',
    description: 'Naval grid battle strategy',
    icon: Anchor,
    category: 'Strategy',
    themeColor: 'cyan',
    bgGradient: 'from-cyan-950/60 via-slate-900 to-slate-950',
    borderColor: 'border-cyan-500/30',
    activeBorder: 'border-cyan-500',
    ringColor: 'ring-cyan-500/50 shadow-cyan-500/20',
    iconBg: 'bg-cyan-500/20 border-cyan-500/40',
    iconColor: 'text-cyan-400',
    badgeVariant: 'blue',
    isImplemented: false,
  },
  {
    id: 'bingo',
    name: 'BINGO',
    description: 'Classic 5×5 line-completing game',
    icon: Grid,
    category: 'Classic',
    themeColor: 'blue',
    bgGradient: 'from-blue-950/60 via-slate-900 to-slate-950',
    borderColor: 'border-blue-500/30',
    activeBorder: 'border-blue-500',
    ringColor: 'ring-blue-500/50 shadow-blue-500/20',
    iconBg: 'bg-blue-500/20 border-blue-500/40',
    iconColor: 'text-blue-400',
    badgeVariant: 'blue',
    isImplemented: true,
  },
  {
    id: 'carrom',
    name: 'CARROM',
    description: 'Flick & pocket strike game',
    icon: Disc,
    category: 'Board',
    themeColor: 'emerald',
    bgGradient: 'from-emerald-950/60 via-slate-900 to-slate-950',
    borderColor: 'border-emerald-500/30',
    activeBorder: 'border-emerald-500',
    ringColor: 'ring-emerald-500/50 shadow-emerald-500/20',
    iconBg: 'bg-emerald-500/20 border-emerald-500/40',
    iconColor: 'text-emerald-400',
    badgeVariant: 'emerald',
    isImplemented: false,
  },
  {
    id: 'checkers',
    name: 'CHECKERS',
    description: 'Diagonal jumping board tactic',
    icon: ShieldAlert,
    category: 'Strategy',
    themeColor: 'rose',
    bgGradient: 'from-rose-950/60 via-slate-900 to-slate-950',
    borderColor: 'border-rose-500/30',
    activeBorder: 'border-rose-500',
    ringColor: 'ring-rose-500/50 shadow-rose-500/20',
    iconBg: 'bg-rose-500/20 border-rose-500/40',
    iconColor: 'text-rose-400',
    badgeVariant: 'rose',
    isImplemented: false,
  },
  {
    id: 'chess',
    name: 'CHESS',
    description: 'Grandmaster 8×8 strategy match',
    icon: Crown,
    category: 'Strategy',
    themeColor: 'amber',
    bgGradient: 'from-amber-950/70 via-slate-900 to-slate-950',
    borderColor: 'border-amber-400/40',
    activeBorder: 'border-amber-400',
    ringColor: 'ring-amber-400/60 shadow-amber-400/30',
    iconBg: 'bg-amber-400/20 border-amber-400/50',
    iconColor: 'text-amber-300',
    badgeVariant: 'amber',
    isImplemented: false,
  },
  {
    id: 'connect4',
    name: 'CONNECT FOUR',
    description: 'Drop discs to connect four in a row',
    icon: Columns,
    category: 'Classic',
    themeColor: 'teal',
    bgGradient: 'from-teal-950/60 via-slate-900 to-slate-950',
    borderColor: 'border-teal-500/30',
    activeBorder: 'border-teal-500',
    ringColor: 'ring-teal-500/50 shadow-teal-500/20',
    iconBg: 'bg-teal-500/20 border-teal-500/40',
    iconColor: 'text-teal-400',
    badgeVariant: 'blue',
    isImplemented: false,
  },
  {
    id: 'dominoes',
    name: 'DOMINOES',
    description: 'Match tile numbers in sequence',
    icon: Boxes,
    category: 'Board',
    themeColor: 'indigo',
    bgGradient: 'from-indigo-950/60 via-slate-900 to-slate-950',
    borderColor: 'border-indigo-500/30',
    activeBorder: 'border-indigo-500',
    ringColor: 'ring-indigo-500/50 shadow-indigo-500/20',
    iconBg: 'bg-indigo-500/20 border-indigo-500/40',
    iconColor: 'text-indigo-400',
    badgeVariant: 'purple',
    isImplemented: false,
  },
  {
    id: 'dots',
    name: 'DOTS & BOXES',
    description: 'Complete boxes and control the board',
    icon: Hexagon,
    category: 'Strategy',
    themeColor: 'purple',
    bgGradient: 'from-purple-950/60 via-slate-900 to-slate-950',
    borderColor: 'border-purple-500/30',
    activeBorder: 'border-purple-500',
    ringColor: 'ring-purple-500/50 shadow-purple-500/20',
    iconBg: 'bg-purple-500/20 border-purple-500/40',
    iconColor: 'text-purple-400',
    badgeVariant: 'purple',
    isImplemented: true,
  },
  {
    id: 'ludo',
    name: 'LUDO',
    description: 'Cross & circle token race',
    icon: Gamepad2,
    category: 'Board',
    themeColor: 'fuchsia',
    bgGradient: 'from-fuchsia-950/60 via-slate-900 to-slate-950',
    borderColor: 'border-fuchsia-500/30',
    activeBorder: 'border-fuchsia-500',
    ringColor: 'ring-fuchsia-500/50 shadow-fuchsia-500/20',
    iconBg: 'bg-fuchsia-500/20 border-fuchsia-500/40',
    iconColor: 'text-fuchsia-400',
    badgeVariant: 'rose',
    isImplemented: false,
  },
  {
    id: 'pool',
    name: 'POOL 8-BALL',
    description: 'Billiards cue ball strategy',
    icon: CircleDot,
    category: 'Arcade',
    themeColor: 'emerald',
    bgGradient: 'from-emerald-950/70 via-slate-900 to-slate-950',
    borderColor: 'border-emerald-400/40',
    activeBorder: 'border-emerald-400',
    ringColor: 'ring-emerald-400/60 shadow-emerald-400/30',
    iconBg: 'bg-emerald-400/20 border-emerald-400/50',
    iconColor: 'text-emerald-300',
    badgeVariant: 'emerald',
    isImplemented: false,
  },
  {
    id: 'reversi',
    name: 'REVERSI (OTHELLO)',
    description: 'Flip opponent discs and dominate',
    icon: RefreshCw,
    category: 'Strategy',
    themeColor: 'teal',
    bgGradient: 'from-teal-950/70 via-slate-900 to-slate-950',
    borderColor: 'border-teal-400/40',
    activeBorder: 'border-teal-400',
    ringColor: 'ring-teal-400/60 shadow-teal-400/30',
    iconBg: 'bg-teal-400/20 border-teal-400/50',
    iconColor: 'text-teal-300',
    badgeVariant: 'emerald',
    isImplemented: false,
  },
  {
    id: 'scrabble',
    name: 'SCRABBLE',
    description: 'Word building tile game',
    icon: Type,
    category: 'Board',
    themeColor: 'amber',
    bgGradient: 'from-amber-950/60 via-slate-900 to-slate-950',
    borderColor: 'border-amber-500/30',
    activeBorder: 'border-amber-500',
    ringColor: 'ring-amber-500/50 shadow-amber-500/20',
    iconBg: 'bg-amber-500/20 border-amber-500/40',
    iconColor: 'text-amber-400',
    badgeVariant: 'amber',
    isImplemented: false,
  },
  {
    id: 'snakes',
    name: 'SNAKES & LADDERS',
    description: 'Dice roll climb & slide race',
    icon: TrendingUp,
    category: 'Classic',
    themeColor: 'indigo',
    bgGradient: 'from-indigo-950/60 via-slate-900 to-slate-950',
    borderColor: 'border-indigo-500/30',
    activeBorder: 'border-indigo-500',
    ringColor: 'ring-indigo-500/50 shadow-indigo-500/20',
    iconBg: 'bg-indigo-500/20 border-indigo-500/40',
    iconColor: 'text-indigo-400',
    badgeVariant: 'purple',
    isImplemented: false,
  },
  {
    id: 'sudoku',
    name: 'SUDOKU DUAL',
    description: 'Head-to-head number puzzle',
    icon: Calculator,
    category: 'Strategy',
    themeColor: 'purple',
    bgGradient: 'from-purple-950/70 via-slate-900 to-slate-950',
    borderColor: 'border-purple-400/40',
    activeBorder: 'border-purple-400',
    ringColor: 'ring-purple-400/60 shadow-purple-400/30',
    iconBg: 'bg-purple-400/20 border-purple-400/50',
    iconColor: 'text-purple-300',
    badgeVariant: 'purple',
    isImplemented: false,
  },
  {
    id: 'tictactoe',
    name: 'TIC TAC TOE',
    description: '3×3 grid duel',
    icon: Hash,
    category: 'Classic',
    themeColor: 'cyan',
    bgGradient: 'from-cyan-950/60 via-slate-900 to-slate-950',
    borderColor: 'border-cyan-500/30',
    activeBorder: 'border-cyan-500',
    ringColor: 'ring-cyan-500/50 shadow-cyan-500/20',
    iconBg: 'bg-cyan-500/20 border-cyan-500/40',
    iconColor: 'text-cyan-400',
    badgeVariant: 'blue',
    isImplemented: false,
  },
  {
    id: 'uno',
    name: 'UNO CARD MASTER',
    description: 'Fast-paced color & number match',
    icon: Sparkles,
    category: 'Cards',
    themeColor: 'rose',
    bgGradient: 'from-rose-950/70 via-slate-900 to-slate-950',
    borderColor: 'border-rose-400/40',
    activeBorder: 'border-rose-400',
    ringColor: 'ring-rose-400/60 shadow-rose-400/30',
    iconBg: 'bg-rose-400/20 border-rose-400/50',
    iconColor: 'text-rose-300',
    badgeVariant: 'rose',
    isImplemented: false,
  },
];

export const getGameById = (id: GameType | null): GameDefinition => {
  const defaultGame = AVAILABLE_GAMES.find((g) => g.id === 'bingo') || AVAILABLE_GAMES[0];
  if (!id) return defaultGame;
  return AVAILABLE_GAMES.find((g) => g.id === id) || defaultGame;
};
